# -*- coding: utf-8 -*-
"""capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OInBlymCN2Q2yRIQGqxqzYTdYwtlh2I9
"""

import streamlit as st
import pandas as pd
import plotly.express as px

#setting up

url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
df = pd.read_csv(url)

df = df.drop(columns=["Province/State", "Lat", "Long"], errors="ignore")
df = df.groupby("Country/Region").sum().T
df.index = pd.to_datetime(df.index)
# df.head()
# df.tail()

daily = df.diff()

st.title("Global COVID-19 Confirmed Cases Dashboard")
st.write("Data from JHU COVID-19 vaccination data hosted on the JHU GovEx GitHub repository")

all_countries = st.checkbox("Show all countries")

if all_countries:
    countries = df.columns
else:
    countries = st.multiselect(
        "Select countries",
        options=df.columns,
        default=["US", "Italy", "Brazil"]
    )

# count type
mode = st.radio("Case type", ["Cumulative", "Daily"])

if mode == "Daily":
    plot_data = daily[countries]
else:
    plot_data = df[countries]

# latest feature
if len(countries) > 0 and len(countries) <= 10:
    latest = plot_data.iloc[-1]
    st.subheader("Latest Values")
    cols = st.columns(len(countries))

    for i, country in enumerate(countries):
        cols[i].metric(country, f"{int(latest[country]):,}")

# time frame selector
start, end = st.slider(
    "Select date range",
    min_value=plot_data.index.min().to_pydatetime(),
    max_value=plot_data.index.max().to_pydatetime(),
    value=(
        plot_data.index.min().to_pydatetime(),
        plot_data.index.max().to_pydatetime()
    )
)

plot_data = plot_data.loc[start:end]

fig = px.line(plot_data, labels={"value": "Cases", "index": "Date"})
st.plotly_chart(fig, use_container_width=True)

